repos:
- repo: local
  hooks:
    - id: check-uv-lock
      name: check uv.lock is up to date
      entry: uv lock --check
      language: system
      files: pyproject.toml
      pass_filenames: false
