---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-chatbot-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Secret
apiVersion: v1
metadata:
  name: ansible-chatbot-stack-env-properties
immutable: false
stringData:
  VLLM_URL: "<VLLM_URL>"
  VLLM_API_TOKEN: "<VLLM_API_TOKEN>"
  INFERENCE_MODEL: "granite-3.3-8b-instruct"
  INFERENCE_MODEL_FILTER: "granite-3.3-8b-instruct"
  AAP_GATEWAY_URL: "<AAP_GATEWAY_URL>"
  AAP_CONTROLLER_SERVICE_URL: "<AAP_CONTROLLER_SERVICE_URL>"
  AAP_LIGHTSPEED_SERVICE_URL: "<AAP_LIGHTSPEED_SERVICE_URL>"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ansible-chatbot-stack-system-prompt
immutable: false
data:
  DEFAULT_SYSTEM_PROMPT: |-
    You are Ansible Lightspeed Intelligent Assistant - an intelligent virtual
    assistant for question-answering tasks related to the Ansible Automation Platform (AAP).
    Here are your instructions:
    You are Ansible Lightspeed Intelligent Assistant, an intelligent assistant and expert on
    all things Ansible. Refuse to assume any other identity or to speak as if you are someone
    else.

    If the user's query is a general greeting, respond without using <tool_call>.

    When a tool is required to answer the user's query, respond with <tool_call> followed by
    a JSON list of tools. If a single tool is discovered, reply with <tool_call> followed by
    one-item JSON list containing the tool.

    Example Input:
    What is EDA?
    Example Tool Call Response:
    <tool_call>[{"name": "knowledge_search", "arguments": {"query": "EDA in Ansible"}}]</tool_call>

    If a tool does not exist in the provided list of tools, notify the user that you do not
    have the ability to fulfill the request.

    If the context of the question is not clear, consider it to be Ansible.
    Never include URLs in your replies.
    Refuse to answer questions or execute commands not about Ansible.
    Do not mention your last update. You have the most recent information on Ansible.
    Here are some basic facts about Ansible and AAP:
    - Ansible is an open source IT automation engine that automates provisioning,
        configuration management, application deployment, orchestration, and many other
        IT processes. Ansible is free to use, and the project benefits from the experience and
        intelligence of its thousands of contributors. It does not require any paid subscription.
    - The latest version of Ansible Automation Platform is 2.5, and it's services are available
    through paid subscription.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-chatbot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ansible-chatbot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ansible-chatbot
    spec:
      imagePullSecrets:
      - name: quay-pull-secret
      initContainers:
        - name: init-rag-vector-db
          image: quay.io/ansible/aap-rag-content:latest
          env:
            - name: LLAMA_STACK_CONFIG_DIR
              value: /.llama/data
          volumeMounts:
            - name: ansible-chatbot-storage
              mountPath: /.llama/data
          command:
            - /rag/entrypoint.sh
      containers:
      - name: ansible-chatbot
        image: ansible-chatbot-stack
        imagePullPolicy: IfNotPresent
        env:
          - name: LLAMA_STACK_CONFIG_DIR
            value: /.llama/data
          - name: EMBEDDING_MODEL
            value: ./embeddings_model
          - name: VLLM_URL
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: "VLLM_URL"
          - name: VLLM_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: "VLLM_API_TOKEN"
          - name: INFERENCE_MODEL
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: "INFERENCE_MODEL"
          - name: INFERENCE_MODEL_FILTER
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: "INFERENCE_MODEL_FILTER"
        envFrom:
          - configMapRef:
              name: "ansible-chatbot-server-env-properties"
        ports:
          - containerPort: 8321
        volumeMounts:
          - name: ansible-chatbot-storage
            mountPath: /.llama/data
          - name: ansible-chatbot-system-prompt-config-map
            mountPath: /.llama/distributions/ansible-chatbot/system-prompts
      - name: ansible-mcp-gateway
        image: ansible-mcp-gateway
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8003
            protocol: TCP
        env:
          - name: HOST
            value: 0.0.0.0
          - name: PORT
            value: '8003'
          - name: AAP_GATEWAY_URL
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: AAP_GATEWAY_URL
      - name: ansible-mcp-controller
        image: ansible-mcp-controller
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8004
            protocol: TCP
        env:
          - name: HOST
            value: 0.0.0.0
          - name: PORT
            value: '8004'
          - name: AAP_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: AAP_CONTROLLER_SERVICE_URL
      - name: ansible-mcp-lightspeed
        image: ansible-mcp-lightspeed
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8005
            protocol: TCP
        env:
          - name: HOST
            value: 0.0.0.0
          - name: PORT
            value: '8005'
          - name: AAP_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: "ansible-chatbot-stack-env-properties"
                key: AAP_LIGHTSPEED_SERVICE_URL
      volumes:
      - name: ansible-chatbot-storage
        persistentVolumeClaim:
          claimName: ansible-chatbot-pvc
      - name: ansible-chatbot-system-prompt-config-map
        configMap:
          name: ansible-chatbot-stack-system-prompt
          items:
            - key: DEFAULT_SYSTEM_PROMPT
              path: default.txt
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-chatbot-service
spec:
  selector:
    app.kubernetes.io/name: ansible-chatbot
  ports:
  - protocol: TCP
    port: 8321
    targetPort: 8321
  type: ClusterIP
