apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ansible-chatbot-deploy.yaml
namespace: ansible-chatbot-stack
images:
- name: ansible-chatbot
  newName: quay.io/ansible/ansible-chatbot
  newTag: aap-0.2.7
