apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ansible-chatbot-deploy.yaml
namespace: ansible-chatbot-stack
images:
- name: ansible-chatbot-stack
  newName: quay.io/ansible/ansible-chatbot-stack
  newTag: 0.0.1
