# sonar.projectKey and sonar.organization are set dynamically
# in .github/workflows/code_coverage.yml based on the repo owner and name

# Python specific settings
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

# Define the same root directory for sources and tests
sonar.sources = .
sonar.tests = tests/

# Include test subdirectories in test scope
sonar.test.inclusions = tests/**/test_*.py

# Exclude test subdirectories from source scope
sonar.exclusions = tests/**/*.py,scripts/**/*.py,.github/**,*.md,*.txt,*.yml,*.yaml,*.json,*.toml,*.lock,Containerfile,Makefile

sonar.qualitygate.wait=true
